Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,9 @@
-name: Build Android App
+name: Build APK
 
 on:
   push:
     branches:
-      - main  # Ваша основная ветка, замените при необходимости
-  pull_request:
-    branches:
-      - main  # Ваша основная ветка, замените при необходимости
+      - main
 
 jobs:
   build:
@@ -16,39 +13,52 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
-    - name: Set up Python
+    - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
-        python-version: '3.x'  # Версия Python
+        python-version: '3.9'
 
-    - name: Install Kivy dependencies
+    - name: Install build dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y \
-          python3-pip \
-          build-essential \
-          git \
-          python3 \
-          python3-dev \
-          ffmpeg \
-          libsdl2-dev \
-          libsdl2-image-dev \
-          libsdl2-mixer-dev \
-          libsdl2-ttf-dev \
-          libportmidi-dev \
-          libswscale-dev \
-          libavformat-dev \
-          libavcodec-dev \
-          zlib1g-dev
+        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-pil python3-setuptools python3-venv python3-wheel python3-xlib
+        pip install kivy cython
 
-    - name: Install buildozer
-      run: pip install buildozer
+    # Accept Android SDK licenses
+    - name: Accept Android SDK licenses
+      run: |
+        yes | sdkmanager --licenses
 
-    - name: Build Android APK
-      run: buildozer android debug
+    # Install Android SDK Build-Tools
+    - name: Install Android SDK Build-Tools
+      run: |
+        sdkmanager "build-tools;35.0.0-rc3"
+
+    # Check for the existence of the build-tools directory
+    - name: Check for build-tools directory
+      run: |
+        if [ ! -d "$HOME/.buildozer/android/platform/android-sdk/build-tools" ]; then
+            echo "build-tools directory not found"
+            exit 1
+        fi
+
+    # Check for Aidl
+    - name: Check for Aidl
+      run: |
+        if ! command -v aidl &> /dev/null
+        then
+            echo "Aidl not found, please install it."
+            exit 1
+        fi
+
+    - name: Build APK
+      run: |
+        python -m pip install --upgrade buildozer
+        buildozer init
+        buildozer -v android debug
 
     - name: Upload APK artifact
       uses: actions/upload-artifact@v2
       with:
-        name: my-app-debug
+        name: app-debug
         path: ./bin/*.apk
